### ISSUE TITLE
Can't add image to new template

### ISSUE THREAD

**Issue by mrgran** [withdave/qlik-sense-icon-generator#10]
When i try to reference a new image i get 404 not found. How do i add new images to the extension?

**Comment by withdave** [comment]
Sorry, missed this, and very stale.

For reference, it should be adding the image to https://github.com/withdave/qlik-icon-generator/tree/master/src/qs-icon-generator/backgrounds, and then specifying it in one of the backgrounds in https://github.com/withdave/qlik-icon-generator/blob/275d0d1a7a12feeac854ec4c503b88e6679d569e/src/qs-icon-generator/config.json#L5
